### ISSUE TITLE
Module Resolution from Custom Paths

### ISSUE THREAD

**Issue by rafegoldberg** [maoberlehner/node-sass-magic-importer#106]
@maoberlehner loving this plugin but struggling to set up module resolution at a custom path, rather than from the `node_modules/` directory. I tried futzing with the `{includePaths}` option (see: #10) but to no avail... 😭 Was wondering how I'd accomplish something like this, if at all possible?

I've set up a very simple Sass project to test– please check out my setup (below) and let me know if you see where I'm going wrong, or if ya have any other suggestions/tips/tricks/etc! Much appreciated in advance.

---

### Files

the main Sass project files live in the `style/` directory, within which I'd like to be able to import the modules from `libs/`.

```
libs/
└── example/
    ├── example.scss
    └── package.json
style/
└── main.scss
```

### Gulp

My `gulp-sass` options read as follows:

```javascript
var
Opts={
  importer: require('node-sass-magic-importer')({
    includePaths:['./bower']
    }),
  includePaths:[
    './node_modules',
    './bower'
    ],
  };//=opts
```

And my compilation task is set up thusly:

```javascript
Gulp.task('css:compile',task=>Gulp.src(Path.src)
  .pipe( sMap.init()                          )
  .pipe( Sass(Opts).on('error',Sass.logError) )
  .pipe( sMap.write()                         )
  .pipe( Gulp.dest(Path.out)                  )
  );//=task[css:compile]
```

 #### Sass

With that setup, I'd expect to be able to use the module resolver in my main Sass files. However, the `@import` call throws an error:

```scss
/*FILE: style/main.scss
 */

@import '~example';//should give a mixin

.test{
  @include example();
  }
```

> **Note**: _relativizing the import path to `lib/example/example.scss` works as expected._

**Comment by rafegoldberg** [comment]
(also PS: the `@import` globbing is a killer feature!)

**Comment by maoberlehner** [comment]
Thank you for the detailed report of your problem – I will look into this ASAP

**Comment by maoberlehner** [comment]
Ok, so what the ~ prefix does is, that it triggers module resolving, which means that `node-sass-magic-importer` will look into your projects `node_modules` directory for a module with the given name. So what you want to do is not possible that way.

What you can do is to add the `lib` directory to your `includePaths` that way you can write `@import 'example/example.scss';` or `@import 'example/example';` if you name the SCSS file `_example.scss`.

I considered to implement support for other package managers like Bower but NPM seems to be "winning" the package manager fight (even on https://bower.io/ yarn and webpack are recommended over Bower since a few days). Also NPM provides the tools for easily resolve the path to modules out of the box.

I will close this issue because I currently have no plans of implementing module resolving for other package managers than NPM or custom directories. Plz feel free to open a new issue with a feature request or recommendations of how to improve the documentation to be more clear about this functionality.

Thank you for using node-sass-magic-importer.

**Comment by rafegoldberg** [comment]
thanks @maoberlehner; definitely no rush on my end.

**Comment by rafegoldberg** [comment]
Hahaha, just saw the Yarn banner over on Bower and was all 🤔... In any case, you're probably right about the aforementioned constraints– no plugin can/should do everything! Appreciate the suggestion– the `node-sass({includePaths})` options with relative `@import` paths seems like it will cover 99% of my use-cases...

And thank _you_ for making `node-sass-magic-importer`!
