### ISSUE TITLE
Dependency package  'get-installed-path' now requires yarn version >=1 

### ISSUE THREAD

**Issue by Swissa** [maoberlehner/node-sass-magic-importer#147]
As you can see here: https://github.com/tunnckoCore/get-installed-path/commit/4dab2e74867736f2f7c31b52bbc001431f20b709

This means that when using your package you also requires yarn version >=1.

**Comment by maoberlehner** [comment]
Do you have set the `engines-strict` config flag? Otherwise specifying the `engines` in the `package.json` file is advisory only (https://docs.npmjs.com/files/package.json#engines).

I just did an `npm install node-sass-magic-importer` and the generated `package-lock.json` file does not include `yarn`. I also can't find `yarn` in the `node_modules` directory. Furthermore I didn't get any warning or error during the installation process and everything is working fine.

So as far is I can see, yarn is not installed as an dependency and installing `node-sass-magic-importer` does not produce any warnings or errors if yarn is not installed on the system.

Please let me know if your experience is different from mine or if I misunderstood the issue. Thank you.

**Comment by Swissa** [comment]
This working fine if you are using `npm install`
The issue I mentioned above occurs only if you are using `yarn` instead of using `npm` as your package manager (https://yarnpkg.com/en/docs/getting-started).

**Comment by maoberlehner** [comment]
What would be the best way to resolve this? Is, what `get-installed-path` is doing the correct way of handling this? If not, shouldn't this be fixed on their side?

**Comment by Swissa** [comment]
`get-installed-path` force every one that using `yarn` to use the latest version of 'yarn' which is a major version.
They can decisions that this is the requirements that they want for if you want to use their package.

The solution can de to limit `get-installed-path`to the previous version, or live with this limitation, and accept this as requirement for this module as well.

**Comment by maoberlehner** [comment]
Thank you for the clarification. This sucks...

I'll think about it, maybe I can remove this dependency completely.

Thank you for informing me about this.
