### ISSUE TITLE
Import only variables and mixins from a specific file

### ISSUE THREAD

**Issue by Lorti** [maoberlehner/node-sass-magic-importer#80]
This is a feature request for an option to only import variables and mixins from a specific file.

This could be similar to http://lesscss.org/features/#import-options-reference and would allow you to reference variables from a different module. 

An example is a header with specific dimensions you might want to use in calculations, without importing the header styles themselves.

That way properties specific to a certain module can be stored with the module itself, instead of putting all variables in a separate file.

**Comment by maoberlehner** [comment]
Cool idea.

I think `@import '[filters] { .selector } file.scss';` could be the syntax.  
Filters could be *variables* and *mixins*. I'd like to call it *filters* instead of *options* because it seems to describe the functionality better and I'd like to use `[]` instead of `()` to be able to implement *options* similar to the LESS stuff at some point in the future.

Although the desired behavior is already possible with `@import '{ } from some/where.scss'` (the whitespace between `{` and `}` is mandatory). But isn't as explicit as `@import '[variables] from some/where.scss'` would be – so I consider to implement this.

Something similar to the *reference* behavior is already possible too: `@import '{ /^[\.|#](.*)/ as %$1 } from some/where.scss'`

```scss
.class-selector { }
#id-selector { }

// after @import '{ /^[\.|#](.*)/ as %$1 } from some/where.scss' becomes:
%class-selector { }
%id-selector { }

// OR after @import '{ /^[\.|#](.*)/ as @mixin $1 } from some/where.scss' becomes:
@mixin class-selector { }
@mixin id-selector { }
// (This is currently not possible because of: https://github.com/maoberlehner/node-sass-selector-importer/issues/24)
```

**Comment by maoberlehner** [comment]
Done: https://github.com/maoberlehner/node-sass-magic-importer#node-filtering
