### ISSUE TITLE
using #{$variable} syntax

### ISSUE THREAD

**Issue by designstorming** [maoberlehner/node-sass-magic-importer#81]
I am currently having problem importing font-awesome icon through this method.

`@import '{ .#{$fa-css-prefix}-close } from ./scss/libs/fontawesome/_icons.scss';`

Is there some "hack" i don't know about or is currently not possible for something like this to be done?
Thanks in advance.

**Comment by maoberlehner** [comment]
I'm sorry but this is not possible. Variables are resolved to their values after all the importing is done – so in the custom node-sass importer there is no way to get the value of the variable. So there is no way to implement this functionality.

**Comment by maoberlehner** [comment]
Sorry, I misunderstood what you want to achieve. I will look into this, thanks for using node-sass-magic-importer.

**Comment by maoberlehner** [comment]
This is fixed by https://github.com/maoberlehner/node-sass-selector-importer/commit/19c26a235f2fa38d5759dd711b45db10b2ca9226

The following is now possible:
```scss
// _icons.scss
.#{$fa-css-prefix}-close { }
```
```scss
@import '{ .#{$fa-css-prefix}-close } from _icons.scss';
```

Run `npm update` to get the latest version of the `node-sass-selector-importer` (this is a dependency of node-sass-magic-importer) and make sure that the latest version of `node-sass-selector-importer` (4.2.0) is installed in your node_modules directory. If not, try to remove the node_modules directory and reinstall your dependencies.

If you are using yarn run `yarn upgrade`

Let me know if everything worked.

**Comment by designstorming** [comment]
@maoberlehner that's it! Thank you a lot <3
